name: notebooks-backend

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    environment:
      - PORT=80
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
